# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgr', models.TextField()),
                ('email', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='prod_mgr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.Productmgr'),
        ),
    ]
