# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuelog', '0008_auto_20180622_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
