# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuelog', '0009_auto_20180622_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ht_product',
            field=models.CharField(choices=[('multifamily', 'multifamly'), ('multi-tenant', 'multi-tenant'), ('mixed-use', 'mixed-use'), ('campus', 'campus'), ('developer', 'developer'), ('note', 'note'), ('other', 'other'), ('website', 'website')], default='other', max_length=15),
        ),
    ]
