# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuelog', '0010_post_ht_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Issue',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='post_status',
            new_name='issue_status',
        ),
    ]
